In [1]:
import numpy as np

In [34]:
adj = np.zeros((4,4))

beta = 0.8

visA = [1,2]
visB = [2]
visC = [0]
visD = [2]

adj[0,visA] = 1.0/len(visA)
adj[1,visB] = 1.0/len(visB)
adj[2,visC] = 1.0/len(visC)
adj[3,visD] = 1.0/len(visD)

leak = np.ones(adj.shape)/adj.shape[0]

final = beta*adj.T + (1.0-beta)*leak
# print(adj)
# print(leak)
print(final)

[[ 0.05  0.05  0.85  0.05]
 [ 0.45  0.05  0.05  0.05]
 [ 0.45  0.85  0.05  0.85]
 [ 0.05  0.05  0.05  0.05]]


In [35]:
vinit = np.ones(4)/4
print(vinit)

[ 0.25  0.25  0.25  0.25]


In [36]:
epochs = 60
v = vinit
for epoch in range(epochs):
    v = np.matmul(final,v.T)
print(v)

[ 0.36320755  0.19528302  0.39150943  0.05      ]
